### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by SimunKaracic** [kitlangton/zio-tui#1]
Hello! This is something that I'd like to contribute to. 
What are some areas that you'd like to work on? 

For me, I'd like to add widgets for everything that can be found in the [lazygit](https://github.com/jesseduffield/lazygit) UI (listview, treeview, these fancy boxes that can have multiple choices (checkout the branches/commits view), popups, all sound like good things to perhaps work on). However, I realise that until then there's probably more groundwork to be done. 

Any chance of having a discussion somewhere so we can define the work needed and start chipping away at it?

**Comment by kitlangton** [comment]
That sounds wonderful, @SimunKaracic! Happy to have a discussion here, Zoom or wherever.

Some things on my to-do list:

- Support both full-screen (e.g., `lazygit`, `brick`) and inline (`scala-interactive-update`, `yarn upgrade-interactive`) UI generation. It already does this, but there are probably some edge-cases. Generally, I need to make sure the `View` type composes correctly in both modes without any glitches.
- A scrolling list view would be great, I already need that when `scala-interactive-update` finds lots and lots of updates.
- Improved rendering. Right now, I wipe and redraw the entire View each render, which can have visual glitches if it's big enough. I have the beginnings of a `diff` method, which should output ANSI `cursorMove` commands and only redraw what has changed. The current `diff` method is a bit buggy.
- Other components like you mentioned would be great as well. A challenge would be figuring out how to make these composable.

**Comment by SimunKaracic** [comment]
A zoom call would probaby be best to start things off, and we can raise issues/plan things out from there. Feel free to send me an email (simunkaracic@gmail.com) and we can figure out a time that fits you

In the meantime I'll dig through this code and and `scala-interactive-update` and try to port a small tool I have to `zio-tui`
